[package]
name = "time_it_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
proc-macro2 = "1.0.95"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lib]
proc-macro = true
